title = "blog.turbo.fish"
base_url = "https://blog.turbo.fish"
description = "Jonas Platte's personal blog"

generate_rss = true
compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
about = """
I am the creator of [turbo.fish][] and [caniuse.rs][]. You may also know me
because of my involvement with the [Ruma][] project.

[turbo.fish]: https://turbo.fish/
[caniuse.rs]: https://caniuse.rs/
[Ruma]: https://www.ruma.io/
"""

[extra.author]
name = "Jonas Platte"
icon_url = "/img/jplatte.png"

[[extra.external_links]]
title = "sourcehut"
a_text = "~jplatte"
a_href = "https://git.sr.ht/~jplatte/"

[[extra.external_links]]
title = "github"
a_text = "jplatte"
a_href = "https://github.com/jplatte"

[[extra.external_links]]
title = "liberapay"
a_text = "jplatte"
a_href = "https://liberapay.com/jplatte/"
