output_dir = "public"

[content."blog/*.md"]
template = "article.html"
process = "markdown_to_html"
date = "{source_file_stem|date_prefix}"
path = "/{source_file_stem|strip_date_prefix}/index.html"

#title = "blog.turbo.fish"
#base_url = "https://blog.turbo.fish"
#description = "Jonas Platte's personal blog"
#
#generate_feed = true
#feed_filename = "rss.xml"

[extra]
about = """
I am the creator of [turbo.fish][] and [caniuse.rs][]. You may also know me
because of my involvement with the [Ruma][] project.

[turbo.fish]: https://turbo.fish/
[caniuse.rs]: https://caniuse.rs/
[Ruma]: https://ruma.dev/
"""

[extra.author]
name = "Jonas Platte"
icon_url = "/img/jplatte.png"

[[extra.external_links]]
title = "sourcehut"
a_text = "~jplatte"
a_href = "https://git.sr.ht/~jplatte/"

[[extra.external_links]]
title = "github"
a_text = "jplatte"
a_href = "https://github.com/jplatte"

[[extra.external_links]]
title = "liberapay"
a_text = "jplatte"
a_href = "https://liberapay.com/jplatte/"
